config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  get 'welcome/index'
  # get '/signin', to: 'auth#signin'
  # post '/signin', to: 'auth#sign_submit'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end

  resources :resumes, only: [:index, :new, :create, :destroy]  

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum:5, maximum:10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/resume.rb
class Resume < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        if session[:user_id]
        @current_user ||= User.find(session[:user_id])
        else
        @current_user = nil
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    http_basic_authenticate_with name: 'admin', password: 'admin123', except: [:index, :show]
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new      
        @article = Article.new  
    end

    def edit
        @article = Article.find(params[:id])
        puts @article
    end

    def create
        @article = Article.new(article_params)
        
        if @article.save
            redirect_to @article
        else 
            render 'new'
        end
    end    

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else 
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to @article
    end    

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
    
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def signin
        
    end

    def signup
    end

    def sign_submit
        
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "admin", password: "admin123", only: :destroy
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
     
    private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all 
  end

  def new
    @resume = Resume.new   
  end

  def create
    @resume = Resume.new(resume_params)
        
    if @resume.save
      redirect_to resumes_path, notice: "Successfully uploaded." 
    else 
      render 'new'
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    redirect_to resumes_path, notice:  "Successfully deleted."  
  end

  private
    def resume_params
      params.require(:resume).permit(:name, :attachment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any?%>
    <div id="error_explain">
      <h2>
        <%= pluralize(@article.errors.count, 'error')%>
          prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div> 
  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: 'form-control' %>
  </div> 
  <div class="bottom">
    <%= submit_tag("save", class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
    <div class="col-12">
        <h1 class="title">All list</h1>
        <%= link_to 'New blog', new_article_path, class: 'custom-tag' %>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th scope="col"># Number</th>
                        <th scope="col">Title</th>
                        <th scope="col">Text</th>
                        <th scope="col" colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @articles.each.with_index do |item, index| %>
                        <tr>
                            <th scope="row"><%= index + 1 %></th>
                            <td><%= item.title %></td>
                            <td><%= item.text %></td>
                            <td><%= link_to raw('<i class="fa fa-eye"></i>'), article_path(item) %> |                 
                                <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_article_path(item) %> |
                                <%= link_to raw('<i class="fa fa-trash"></i>'), article_path(item),
                                    method: :delete,
                                    data: {confirm: 'Are you sure?'} %>
                            </td>
                        </tr>   
                    <% end %>
                </tbody>
            </table>
        </div>            
    </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-12">
    <h1 class="title">New</h1>
    <%= render 'form' %>
    <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<h1 class="title">Show</h1>
<p>
  <strong>Title</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Text</strong>
  <%= @article.text %>
</p>
<h2>Commets</h2>
<%= render @article.comments %>
<h2>add comment:</h2>
<%= render 'comments/form' %>
<%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'List', articles_path%>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :commenter %>
    <%= form.text_field :commenter, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <div>
    <%= submit_tag("Create Comment", class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<div class="row">
    <div class="col-12">
        <% if !flash[:notice].blank? %>   
        <div>   
            <%= flash[:notice] %>   
        </div>   
        <% end %>   
        
        <br>   
        
        <%= link_to "New Resume", new_resume_path %>   
        <br>   
        <br>   
        <div class="table-responsive">
            <table class="table table-hover table-striped">   
                <thead>   
                    <tr>   
                        <th>Candidate Name</th>   
                        <th>Download Link</th>   
                        <th>Action</th>   
                    </tr>   
                </thead>   
                    
                <tbody>   
                    <% @resumes.each do |resume| %>   
                            
                        <tr>   
                            <td><%= resume.name %></td>   
                            <td><%= link_to  image_tag(resume.attachment_url, class: 'img-thumbnail'), resume.attachment_url %></td>   
                            <td><%= link_to "Delete",  resume,
                                    method: :delete,
                                    data: {confirm: "Are you sure you want to delete #{resume.name}?"} %></td>   
                        </tr>   
                            
                    <% end %>   
                </tbody>   
                
            </table>
        </div>
    </div>
</div>

app/views/resumes/new.html.erb
<h1>Resumes#new</h1>
<div class="row">
  <div class="col-12">
    <% if !@resume.errors.empty? %>   
      <div id="error_explain">   
        <h2>
          <%= pluralize(@resume.errors.count, 'error')%>
            prohibited this resume from being saved:
        </h2>
        <ul>   
          <% @resume.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
          <% end %>   
        </ul>   
          
      </div>   
    <% end %>

    <%= form_for @resume, html: { multipart: true } do |f| %> 
      <div class="form-group">  
        <%= f.label :name %>   
        <%= f.text_field :name, class: 'form-control' %> 
      </div>  
      <div class="form-group">    
        <%= f.label :attachment %>   
        <%= f.file_field :attachment, class: 'form-control' %> 
      </div>  
      <br>   
      <%= submit_tag("save", class: 'btn btn-primary') %> 
    <% end %> 
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-12">
    <%= link_to 'Users', controller: 'users' %>
    <%= link_to 'My blog', controller: 'articles' %>
    <%= link_to 'File upload', controller: 'resumes' %>
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to 'Log Out', logout_path %>
    <% else %>
      <%= link_to 'Sign Up', signup_path %> or 
      <%= link_to 'Log In', login_path %>
    <% end %>
    <p id='notice'><%= notice %></p>
  </div>
</div>